In [2]:
import numpy as np
L = [1,2,3]
A = np.array([1,2,3])
for e in A:
    print(e)

A + np.array([4]) # broadcasting
A + np.array([4,5,6]) # adding vectors of same length
#A + np.array([4,5]) # error 

2*A

1
2
3


array([2, 4, 6])

In [3]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print(data)
print(data*10)
print(data + data)
print(data.shape)
print(data.dtype)
m = np.array([[1, 2, 3], [4, 5, 6]])
print(m.dtype)

mylist = [1, 2, 3, 4, 5]
x = np.array(mylist)
print(x.shape)

np.empty((2, 3, 2))
np.ones((2, 3, 2))
print(np.eye(3))


arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]
[[ 15.  -1.  30.]
 [  0. -30.  65.]]
[[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]
(2, 3)
float64
int64
(5,)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
int64
float32


In [14]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr * arr)
print(arr - arr)
print(1 / arr)
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2 > arr)

arr = np.arange(10)
print(arr)
print(arr[5:8])
arr[5:8] = 12
print(arr)
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr)
arr_slice[:] = 64
print(arr)

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0, 2] # same as arr2d[0][2]
print(arr2d[:2, 1:]) # first two rows, last two columns
print(arr2d[:, :1]) # first column

[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[False  True False]
 [ True False  True]]
[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[    0     1     2     3     4    12 12345    12     8     9]
[ 0  1  2  3  4 64 64 64  8  9]
[[2 3]
 [5 6]]
[[1]
 [4]
 [7]]
